### ISSUE TITLE
Error 126

### ISSUE THREAD

**Issue by biaxz** [TomKein/Mql4Copier#1]
Recently I build your source to DLL but error when load to MT4 

2017.02.23 14:33:54.161	Cannot call 'testMQL4.dll::ffc_Init', 'testMQL4.dll' is not loaded

**Comment by TomKein** [comment]
Hi, its project not for public =)
what your interest?

**Comment by biaxz** [comment]
Hahaha, OK no problem, I'm searching Poco library and found your source using NamedMutex.h

**Comment by TomKein** [comment]
=)
